/*
 * This file is generated by jOOQ.
 */
package gim.postgresql.jooq.model;


import gim.postgresql.jooq.model.tables.Member;
import gim.postgresql.jooq.model.tables.records.MemberRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MemberRecord> MEMBER_PKEY = Internal.createUniqueKey(Member.MEMBER, DSL.name("member_pkey"), new TableField[] { Member.MEMBER.ID }, true);
}
