/*
 * This file is generated by jOOQ.
 */
package gim.postgresql.jooq.model;


import gim.postgresql.jooq.model.tables.Member;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;
}
